== Overview

The workflow ID will be constructed in one way and thus a central location that
handles that behavior is required.

== Context

JavaScript does not encompass the same variable types that Solidity does meaning
we cannot have the JS generate the ID and send it down to the contracts for
storage.

In the future there may be cases where automated systems act on behalf of
individuals based on authorization and that would lead to similar code being
implemented in Solidity - leading to 2 versions of ID generation to maintain.

To centralize the functionality it should be kept in Solidity as a "functionality
provider" which enables the front end to create workflow ID's and make simple
queries.

There are two approaches
. Concatenate the strings in JS and send them to a function and have it unpack
the data
. Loop through the functions and send them sequentially to the processor. Once
all the data is sent call another function to process that stored array information.

The single call approach may be more costly as it will require additional conversions
and looping over individual characters to figure out how to split the functions.

If the multi-call approach does not receive the "finish" signal the next time
the user tries to alter the workflow there may be issues.


== Requirements

. Function that accepts a string representation of a function and its data types
that adds it to an array of workflow functions used for ID generation

. Function that when called will generate the ID from the data in the array.
Empty the array after the ID is created
// TODO: concat functions, somehow need to create and manage a NONCE..., query
// the ID registry to check for collision creating a tight coupling of contracts...
// need to store and return some value to UI to let the user know... smh
