# TODO

- detail the nonce that will be appended to the end of the workflow ID
- assuming that this is all through a GUI therefore execution may differ if this is automated
- assuming that the workflow is a fully contained box meaning they also supply the values to the functions and not just the types
- if they delete the workflow then when they refresh the page the service registry will display the workflow ID instead of the human readable name since that no longer exists
- what data do we actually have when we see our workflows? if we have the ID as well as the name then we can simply use the ID without doing any lookups in the workflow registry

== Overview

The user controller is the central point that the user will use to add/edit/remove
workflows and execute them.

== Requirements

. A user should be able to add a new workflow
.. The workflow must have an ID associated with it that is
... Unique
... Bytes type and is made from the function selectors in their specified order
in addition to a nonce
.. The workflow ID should be added to the workflow registry mapping
.. The workflow should be added to the workflow database

. A user should be able to edit an existing workflow
.. The human readable name should be editable
.. The functions and their arguments should be editable

. A user should be able to remove an existing workflow
.. Either delete all references / objects or mark the workflow as non-existent
so that it can be overwritten (move into implementation?)

. A user should be able to view all of their workflows

. A user should be able to associate a workflow ID with a contract in the
service registry

. A user should be able to remove the mapping from the service registry

. A user should be able to edit the mapping in the service registry

. A user should interact with their workflows via a human readable name while
the system uses the workflow ID to perform its actions

. A user should be able to execute a workflow if it is in their workflow database
and is associated with a contract via the service registry


== Implementation suggestions

A user should be able to add a new workflow::
. Take each function signature and turn it into a function selector consisting
of the most significant 4 bytes
. Concatenate the function selectors in sequential order which is provided by the
user and store this as a local variable ready for possible reuse.
. Generate a nonce.
. Append the nonce to a copy of the concatenated function selectors.
. Check the workflow registry to see if the workflow ID is unique.
.. The workflow registry should have a getter for this
.. If not unique then regenerate nonce and start again by appending to the copy.
. Create a mapping in the workflow registry
.. string of human readable name => workflow ID
.. workflow ID => human readable name
. Store workflow in workflow database via a mapping of the workflow ID to data
.. The database should have functions for this, do not proxy it via registry

A user should be able to edit an existing workflow::
The following is broken down into 2 sections for clarity and not because the user
is forced to only change one option or the other
. Workflow human readable name change
.. Delete the mapping in the workflow registry for the old name => workflow ID
.. Create a new mapping for the new name => workflow ID
.. Update the value for the workflow ID
. Functions and arguments
.. The workflow ID be different therefore generate a new unique ID
.. delete the old mapping in the workflow registry
.. create a new mapping in the workflow registry
.. delete the old data in the database mapping
.. create the new entry into the database

A user should be able to remove an existing workflow::
. Remove the mapping from the workflow registry
. Remove the data from the database

A user should be able to view all of their workflows::
. Functions should be atomic therefore you ask for something specifically and have
that returned rather than looping and it somehow returning everything
. This implies getter functions which keep track of the number of workflows such
that the front end can then iterate over the same function with a new ID

A user should be able to associate a workflow ID with a contract in the service registry::
. Use the human readable name to fetch the workflow ID from the workflow registry
and map that in the service registry to the contract address that they specify

A user should be able to remove the mapping from the service registry::
. Use the human readable name to fetch the workflow ID from the workflow registry
and delete the mapping

A user should be able to edit the mapping in the service registry::
. Replace the value for the workflow ID key from one contract address to another

A user should interact with their workflows via a human readable name while the system uses the workflow ID to perform its actions::
. If we are using the ID then do a reverse lookup in the workflow registry to get the name

A user should be able to execute a workflow if it is in their workflow database and is associated with a contract via the service registry::
. Check via the workflow registry to see if the workflow exists
. Check the service registry to see if there is a contract to execute upon
. If both conditions are met then execute via the batcher else return the gas
