== Overview

In order to execute a workflow there must be an end point location (a contract)
which is called with the functions and arguments that are contained within the
workflow.

The service registry will be a contract which stores the information associated
between the workflow ID and which contract it should act upon.

== Requirements

. The registry must contain a mapping from a workflow ID => contract address

. Adding a non-unique ID should revert and return the gas

. 1 workflow ID per 1 contract address

. The contract address (value) can be associated to many different workflow ID's (key)

. A workflow ID (key) can have its contract (value) changed to another contract address

. A workflow ID can be replaced with a different workflow ID while retaining its contract value

== Implementation suggestions

The registry must contain a mapping from a workflow ID => contract address::
. Simple mapping between bytes => address should be sufficient

Adding a non-unique ID should revert and return the gas::
. If the ID is already in a mapping when we try to "re-add" it then revert

1 workflow ID per 1 contract address::
. This is to prevent having a workflow ID associated to many contracts and us
not knowing which to execute upon (plus looping)

The contract address (value) can be associated to many different workflow ID's (key)::
. The workflow ID must be a unique key however the value, being the contract address,
can be associated to any number of workflow ID's

A workflow ID (key) can have its contract (value) changed to another contract address::
. Replace the value in the mapping

A workflow ID can be replaced with a different workflow ID while retaining its contract value::
. If we want to use a different workflow for this contract then we should be able to
replace the previous workflow ID to a new one
